---
- name: reload daemon
  service: 
    name: daemon_reload

- name: start nginx
  service: 
    name: nginx 
    state: started
    enabled: yes

- name: restart nginx
  service: 
    name: nginx 
    state: restarted
    enabled: yes




 