---

- name: Criando diretório
  file:
      path: /var/www/html/blog
      recurse: yes 
      state: directory
      owner: nginx
      group: nginx
      mode: '0755'
      
        
- name: Download Wordpress
  get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/blog/

- name: Extrair arquivo
  unarchive: 
          src: /var/www/html/blog/wordpress-5.3.tar.gz
          dest: /var/www/html/blog/
          remote_src: yes

- name: Change file ownership, group and permissions
  file:
    path: /var/www/html/blog/wordpress
    owner: nginx
    group: nginx
    mode: '0755'

##- name: Move foo to bar
#   command: mv /var/www/html/blog/wordpress/wp-config-sample.php /var/www/html/blog/wordpress/wp-config.php

- name: Copiar arquivo de wp-config do blog para a pasta do wordpress
  template:
        src: wp-config.j2
        dest: /var/www/html/blog/wordpress/wp-config.php
  notify: restart nginx
